# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
title: scikit-learn Blog
email: social@scikit-learn.org
description: "Official blog for scikit-learn, an open source package for machine learning in Python."

logo: assets/images/scikit-logo.png
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://scikit-learn.github.io/blog/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scikit_learn
github_username:  scikit-learn
repository: scikit-learn/blog

header:
  image: /assets/images/scikit-header.png

# Site-wide Search
search: true

# Format Dates
date_format: "%Y-%m-%d"

# Author
author:
  #name: ""
  #avatar: "/assets/images/"
  bio: "Open source machine learning in python."
  #location: ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://scikit-learn.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/scikit_learn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/scikit-learn"

# Site Footer
# social media logos and handles
#footer:
#- title: Connect
#  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/scikit_learn
#    - label: "LinkedIn"
#      icon: "fab fa-fw fa-linkedin"
#      url: "https://linkedin.com/company/scikit-learn/"
#    - label: "Facebook"
#      icon: "fab fa-fw fa-facebook"
#      url: "https://facebook.com/scikitlearnofficial/"
#    - label: "Youtube"
#      icon: "fab fa-fw fa-youtube"
#      url: "https://youtube.com/channel/UCJosFjYm0ZYVUARxuOZqnnw"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://www.instagram.com/scikitlearnofficial/"


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: minimal-mistakes-jekyll

# Skin: determines site color theme
minimal_mistakes_skin: "air" 
# "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# SEO Related
#google_site_verification : 
#bing_site_verification   :
#yandex_site_verification :
#naver_site_verification  :

# Google Analytics
#analytics:
#  provider: "google" #false # false (default), "google", "google-universal", "custom"
#  google:
#    tracking_id: #UA-XXXXXXXX

# Exclude from processing
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: false
      related: true
      comments: true
      share: false
      author_profile: true
