# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
title: scikit-learn Blog
email: social@scikit-learn.org
description: "Official blog for scikit-learn, an open source package for machine learning in Python."

logo: assets/images/scikit-learn-logo.png
favicon: assets/images/scikit-learn-logo.png
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://scikit-learn.github.io/blog/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scikit_learn
github_username:  scikit-learn
repository: scikit-learn/blog

header:
  image: /assets/images/scikit-header.png

# Site-wide Search
search: true

# Format Dates
date_format: "%Y-%m-%d"

# Author
author:
  #name: ""
  #avatar: "/assets/images/"
  bio: "Open source library for machine learning in Python."
  #location: ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/scikit-learn"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/scikit_learn"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/channel/UCJosFjYm0ZYVUARxuOZqnnw"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/company/scikit-learn/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/scikitlearnofficial/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/scikitlearnofficial/"


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/scikit-learn"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/scikit_learn"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://youtube.com/channel/UCJosFjYm0ZYVUARxuOZqnnw"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/company/scikit-learn/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/scikitlearnofficial/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/scikitlearnofficial/"


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: minimal-mistakes-jekyll

# Skin: determines site color theme
minimal_mistakes_skin: "air" 
# "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-archives

# SEO Related
#google_site_verification : 
#bing_site_verification   :
#yandex_site_verification :
#naver_site_verification  :

# Google Analytics
#analytics:
#  provider: "google" #false # false (default), "google", "google-universal", "custom"
#  google:
#    tracking_id: #UA-XXXXXXXX

# Exclude from processing
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Archives
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
     category: archive-taxonomy
     tag: archive-taxonomy
  permalinks:
     category: /categories/:name/
     tag: /tags/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar:
        nav: "docs"
      show_date: true
      read_time: false
      related: true
      comments: true
      share: true
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
